# -*- coding: utf-8 -*-
"""data visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uzg1VV7dGQKqZOLFkJF19vy6aa6rVosI
"""

import pandas as pd
import matplotlib.pyplot as plt

df= pd.read_csv("realistic_sales_dataset.csv")
df.hist()
plt.show()

labels= ['apples', 'bananas', 'cherries', 'dates']
data= [30,20,35,15]
plt.pie(data, labels=labels)
plt.title('fruit distribution')
plt.show()

plt.scatter(df['quantity'], df['price'])
plt.show

x= [1,2,3,4,5]
y= [2,4,6,8,10]
plt.plot(x,y)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('line chart')
plt.show()

df.plot.bar()
plt.bar(df['quantity'], df['price'])
plt.show()



